[git]
  autoCommit = true
  autoPush = true
  commitMessageTemplate = "{{ promptString \"Commit message\" }}"

[merge]
    command = "meld"
    args = [
        "{{ .Destination }}",
        "{{ .Source }}",
        "{{ .Target }}",
    ]
